### ISSUE TITLE
RAM and time to run on the included test data

### ISSUE THREAD

**Issue by tseemann** [gtonkinhill/rhierbaps#2]
Gerry,

A colleague ran `rhierbaps` on 1 core with the test data (which seems to be about 500 samples x 3000 sites), and it took **2 days** to complete.

Does this sound correct?
How much RAM does it need?   (as a function of of samples, sites, ...)
Does it need the full alignment, or just the variant sites?

Any help appreciated!

Torsten

**Comment by gtonkinhill** [comment]
Hi Torsten,

That seems strange, it takes about 2 minutes on my macbook. I've added timing information for the test dataset to the vignette d617c47

The `load_fasta` function by default filters out all invariant sites and those SNPs that are only found in one sample so supplying just the variant sites is perfectly okay.

The RAM scales pretty terribly with the number of cores as for now it just naively creates copies of the matrices. The memory requirements are also slightly worse than the MATLAB code as I make use of doubles. Otherwise it should be a linear multiple of the input matrix memory requirements so double precision * number of SNPs * number of Samples * constant. 

So far for very large matrices >100,000 SNPs >1000 samples the MATLAB version appears to be more efficient. However, I'm hoping to find some time to improve this.

**Comment by tseemann** [comment]
Thanks Gerry - that is very informative.   I agree, It seemed far too long, hence this question. 

The user was giving it 1500 samples x 3,000,000 sites, of which ~300,000 (maybe) were variant, with 63 cores.   I am told they have contacted you via email, hopefully they sort it out and we won't have to use `kill -9` again :)
